# Using {{ "}}" }} to escape the templating used by appsets.
{{- range .Values.repos }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $.Values.cluster }}-{{ $.Release.Name }}-{{ . | trimSuffix "-deploy" }}
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: 'https://github.com/{{ $.Values.githubOrg | default $.Release.Name }}/{{ . }}'
      revision: HEAD
      directories:
        - path: {{ $.Values.path }}
  template:
    metadata:
      #name: {{ $.Values.cluster }}-{{ $.Release.Name }}-{{ . | trimSuffix "-deploy" }}-{{ "{{" }}path.basename{{ "}}" }}
      name: 'team-{{ $.Release.Name }}'
      # annotations:
      #   notifications.argoproj.io/subscribe.on-deployed.github: ""
    spec:
      #project: {{ $.Values.cluster }}-{{ $.Release.Name }}
      project: default
      source:
        repoURL: 'https://github.com/{{ $.Values.githubOrg | default $.Release.Name }}/{{ . }}'
        targetRevision: 'HEAD'
        path: '{{ "{{" }}path{{ "}}" }}'
        ## Rendered manifests.
        # targetRevision: '{{ "{{" }}path{{ "}}" }}'
        # path: './'
      destination:
        name: '{{ $.Values.cluster }}'
        #namespace: '{{ $.Release.Name }}-{{ "{{" }}path.basename{{ "}}" }}'
        namespace: 'team-{{ $.Release.Name }}'
      syncPolicy:
        automated: {}
{{- end }}